tasks:
  - name: Setup and Build
    before: |
      # Download and Install Java 17.0.6-tem
      yes Y | sdk install java 17.0.6-tem

      # Download and Install 18.14.2
      VERSION="18.14.2" \
      && source $HOME/.nvm/nvm.sh && nvm install $VERSION \
      && nvm use $VERSION && nvm alias default $VERSION

      # Download and Install Maven 3.9.0
      VERSION="3.9.0" &&\
      yes Y | sdk install maven $version
    init: |    
      #Build using Maven
      mvn package -Dmaven.test.skip
        