tasks:
  - name: Setup and Build
    before: |
      # Download and Install Java 21.0.1-tem
      yes Y | sdk install java 21.0.1-tem

      # Download and Install Maven 3.9.6
      yes Y | sdk install maven 3.9.6
    init: |
      # Build using Maven
      mvn package -Dmaven.test.skip

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
