tasks:
  - init: |
      # Install Java 17.0.6-tem
      yes Y | sdk install java 17.0.6-tem

      # Set Node.js to 18.14.0
      VERSION="18.14.0" \
      && source $HOME/.nvm/nvm.sh && nvm install $VERSION \
      && nvm use $VERSION && nvm alias default $VERSION

      yarn install

      mvn package -Dmaven.test.skip