tasks:
  - init: |
      # Install Java 17.0.6-tem
      sdk install java 17.0.6-tem
      
      # Set default Java version
      yes | sdk default java 17.0.6-tem
      
      # Install dependencies, build project, and run tests
      yarn install
      yarn run build
      ./mvnw install -DskipTests=false
