spring:
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties.hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc.lob.non_contextual_creation: true
        open-in-view: false

management:
    endpoints.web.exposure.include: health,info
    info:
        git.enabled: true
        build.enabled: true

jenkins.update-center: https://updates.jenkins.io/current/update-center.actual.json
github.oauth: ${GITHUB_OAUTH}
cron:
    update-center: ${UPDATE_CENTER_CRON}
    probe-engine: ${PROBE_ENGINE_CRON}

---

spring.config.activate.on-profile: dev
logging.level:
    io.jenkins.pluginhealth: DEBUG
