name: ✨ New probe
description: Request a new probe to be implemented on the project
labels: [probe, enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a new probe idea.
        Please know that we will take every submission in consideration, but not all idea might be implemented.

        Please make sure the title provided is a summary of the purpose of the desired probe.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please describe as precisely as possible what data you are expected this new probe to fetch.
        If you can, please help us to know where is data can be found and how it should be use to score a plugin.
    validations:
      required: true
