name: ✨ New probe
description:
labels: [probe, enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you fo taking the time to submit a new probe idea.
        Please know that we will take every submission in consideration, but not all idea might be implemented.
  - type: input
    id: title
    attributes:
      label: Title
      description: "A clear and concise summary of the probe expected behavior."
      placeholder: "Example: Retrieve the number of issue reported against the plugin."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please description as precisely as possible what data you are expected this new probe to fetch.
        If you can, please help us to know where is data can be found and how it should be use to score a plugin.
      render: AsciiDoc
    validations:
      required: true
