= Contributing to Plugin Health Scoring

This page provides information about contributing to the Plugin Health Scoring code base.

== Getting started

The project is using Maven with Java 21 and Yarn to be built.
The entire build process can be handled by Maven.
When building, Yarn will bundle the front-end files only.

. Clone the repository.
. Install tools
.. Java 21
.. Maven 3.9.9
.. Node 22.14.0 and Yarn 4.7.0 (these should be done in the "war" directory)
.. Docker installed and running in your environment
. Open the project in your favorite IDE.

NOTE: Optionally, you can use the Maven wrapper in the repository.
In that case, replace the `mvn` command by `./mvnw` in the command listed bellow.

WARNING: Make sure that you follow the instruction to install Yarn 2+.
See https://yarnpkg.com/getting-started/install.

Please see the link:ARCHITECTURE.adoc[architecture] document to better understand the structure of the code.

== How to build locally the application

Once you have installed the tools listed before, you can generate the application binary by running the command, but bewware of additional requirements in the xref:how-to-run-the-application-locally[next subsection]:

[source,bash]
----
mvn verify
----

This will run all the tests of the application.
You can speed up the process by running the command:

[source,bash]
----
mvn package -Dmaven.test.skip
----

[#how-to-run-the-application-locally]
=== How to run the application locally

Before starting the application, it is required to create a GitHub App, configure environment variables and have access to a PostgreSQL Database.

==== Environment variables

You can find the list of environment variables in link:.env.example[].

[source,bash]
----
include::.env.example[]
----

==== GitHub App

We also need to setup a GitHub application because of the number of API calls that happen from our application back to GitHub. If we didn't setup the GitHub application, we could run into a token exhaustion scenario which causes our app to effectively quit working until more tokens are made available to us to use.

To create the GitHub App, please see link:https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app[]

The application requires the following permissions:

* Repository content (read-only)

Once the GitHub APP created, generate a private key.
It will be downloaded automatically.

The downloaded key needs to be converted using the following command:

[source,bash]
----
openssl pkcs8 -topk8 -inform PEM -outform PEM -in ORIGINAL_KEY.pem -out CONVERTED_KEY.pem -nocrypt
----

NOTE: You need to change `ORIGINAL_KEY` and `CONVERTED_KEY` with real values.

This final file is the one to point to in `GITHUB_APP_PRIVATE_KEY_PATH` environment variable.

Finally, you need to install the GitHub APP on your GitHub user.
In the GitHub App configuration page, find the *Install App* link on the left side menu.

==== Starting a PostgreSQL database

If you don't want to install a PostgreSQL database locally, it is possible to start the service in the Docker Compose configuration.

In order to start the database this way, you can run the following command:

[source,bash]
----
docker compose up -d db
----

==== Running the application from CLI

This method is preferred if you intend to submit any modifications to the project.

In one terminal, run:

[source,bash]
----
cd ./war
yarn install
yarn dev
----

This will build and update the front-end files when you modify them.

First remember to run `mvn clean install` at root. Then, at the `war directory`, in a second terminal run:

[source,bash]
----
mvn spring-boot:run -Dskip.yarn -Dspring-boot.run.profiles=dev
----

This will start the application.

NOTE: Don't forget to set the required environment variables.

==== Running the application with Docker Compose

If you want to simply run the project locally, you can run:

[source,bash]
----
mvn package -Dmaven.test.skip
docker compose up
----

NOTE: the required environment variables must be set in a file named `.env`.

==== Connecting to database with Docker container

If you are using Docker you can connect to the database using the following command:

[source,bash]
----
docker container exec -it plugin-health-scoring-db-1 psql -U <postgres-user-name>
----

==== Not using `cron` when doing development

There are a few components that use `@Scheduled` in the app. This can be a pain to work with while doing development:

There are 2 classes that use `@Scheduled` in the app:

* `war/src/main/java/io/jenkins/pluginhealth/scoring/schedule/UpdateCenterScheduler.java`
* `war/src/main/java/io/jenkins/pluginhealth/scoring/schedule/ProbeEngineScheduler.java`

NOTE: There is actually a third file (`war/src/main/java/io/jenkins/pluginhealth/scoring/schedule/DeleteOldScoreScheduler.java`), but that doesn't really matter for development.

You have a choice. You can choose to always update the cron value in your `.env` file or while in development, you can change the `@Scheduled` value to something like:

`@Scheduled(initialDelay = 10 * 1000 /* 10 secs after startup */, fixedDelay = 1000 * 60 * 90 * 1)`

What this means is the initial delay will be 10 seconds, and then after that initial run, it will run every 90 minutes. Tweak the values to whatever you want, but leave the `initialDelay` in so you don't have a race condition on startup.

WARNING: DO NOT COMMIT the `@Scheduled` changes.

== Run the application on Gitpod

Gitpod is a cloud-based IDE that allows developers to write, test, and deploy code from anywhere.
Follow this link to get familiar with Gitpod: link:https://www.gitpod.io/docs/introduction/getting-started[Getting Started with Gitpod]

This project includes a configuration in `.gitpod.yml` to be able to contribute to it on Gitpod.
The required versions of Java and Maven are installed when starting the Gitpod workspace.

In order to run the project within the Gitpod environment, follow the steps of running the application with Docker Compose.

NOTE: In case the build fails on start, run `mvn package -Dmaven.test.skip` again.

== Testing change

The project has unit and integration tests.
You can run all those with

[source,bash]
----
mvn verify
----

WARNING: The integration tests requires Docker to be installed.

== Proposing changes

All proposed changes are submitted and reviewed through a GitHub pull request.
To submit a pull request:

. Make sure your changeset is not introducing a regression by running `mvn verify`
. Create a branch prefixed with:
.. `feature/` for a new enhancement
.. `fix/` for a bugfix
.. `docs/` for documentation changes
. Commit your changes to this new branch
. Push the branch to your fork of the repository.
. In the GitHub Web UI, select the *New pull request* option
. Follow the pull request template
. Click the _Create pull request_ button.

The pull request will be built in link:https://ci.jenkins.io[ci.jenkins.io].

== Releases

The releases can be generated by using the `release.sh` script at the root of the repository.
This script uses `git`, `gh`, `jq` and `mvn` to generate the release.
The script also requires your Bash version to be greater than 4.
Make sure you have all those tools on your system.

You can run the script like this:

[source bash]
----
bash release.sh
----

WARNING: To be able to perform a release, you **must** have write permission on the project repository.

The script will pick the version from the GitHub Release in draft which is prepared by `release-drafter`.

You can pass a version as the first argument of the script, but only if you know exactly what you are doing.
Then, run the script like:

[source bash]
----
bash release.sh 9.9.9
----

The project doesn't publish a Java binary.
The release is "only" generating a Git tag, changing the versions in the `pom.xml` files.
The tag is picked up by infra.ci.jenkins.io to build the docker image.

When both the docker image and the GitHub Release are available, Infra team has a Jenkins job using `updatecli` which will create a pull request on link:https://github.com/jenkins-infra/helm-charts[].
This pull request should be reviewed carefully.
Once it is merged, a deployment will be triggered through a pull request on the link:https://github.com/jenkins-infra/kubernetes-management[] repository.
The new release is *only* deployed on the infra system and available at link:https://plugin-health.jenkins.io[] when this second pull request is merged.
