name: Release Drafter
on:
  push:
    branches:
      - main
# Only allow 1 release-drafter build at a time to avoid creating multiple "next" releases
concurrency: "release-drafter"
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@c2e2804cc59f45f57076a99af580d0fedb697927 # v7.3.0
        with:
          # This token is generated automatically by default in GitHub Actions: no need to create it manually
          token: ${{ secrets.GITHUB_TOKEN }}
